export const actionTypes = {
    SHOW_MODAL : "SHOW_MODAL",
    CLOSE_MODAL: "CLOSE_MODAL",
    ALLOW_CLOSE: "ALLOW_CLOSE",
    SELF_CLOSE: "SELF_CLOSE",
    REPLACE_MODAL: "REPLACE_MODAL",
    CHANGE_STATUS_MODAL: "CHANGE_STATUS_MODAL"
}